const mockOrders = [
	{
		orderId: '920201',
		customer: {
			customerData: {
				name: 'Wiesław',
				lastname: 'Paleta',
			},
			contact: {
				email: 'wieslaw@paleta.tech',
				phoneNumber: '+48666666666',
			},
			address: {
				address1: 'Bruklin 23',
				address2: '',
				postalCode: '99-054',
				country: 'Polska',
			},
		},
		order: {
			cart: {
				items: [
					{
						categoryID: 44,
						description: '',
						discount: 7.5,
						format: 'Płyta CD',
						id: '497',
						img: 'https://ecsmedia.pl/c/collapsed-in-sunbeams-w-iext120309470.jpg',
						price: 39.99,
						releaseYear: '2021',
						title: 'Collapsed in Sunbeams',
						type: 'albums',
						label: 'Transgressive',
						authors: ['Arlo Parks'],
					},
					{
						categoryID: 41,
						description: '',
						discount: 5,
						format: 'Płyta CD',
						id: '528',
						img: 'https://ecsmedia.pl/c/ala-w-iext104665163.jpg',
						price: 34.99,
						releaseYear: '2016',
						title: 'AŁA.',
						type: 'albums',
						label: 'Alkopoligamia',
						authors: ['Ten Typ Mes'],
					},
				],
				qty: 2,
				value: 72.38000000000001,
			},
			ship: {
				inpost: 'GDA77M',
			},
		},
	},
	{
		orderId: 'fc7234',
		customer: {
			customerData: {
				name: 'Eustachy',
				lastname: 'Parafia',
				nip: '1234567890',
				companyName: 'Eustachy Parafia IT Service',
			},
			contact: {
				email: 'eustachy@parafia.pl',
				phoneNumber: '+48777222334',
			},
			address: {
				address1: 'Puławska 7/44',
				address2: '',
				postalCode: '01-045',
				country: 'Polska',
			},
		},
		order: {
			cart: {
				items: [
					{
						categoryID: 10,
						description: '',
						discount: 0,
						format: 'Książka (miękka okładka)',
						id: '106',
						img: 'https://ecsmedia.pl/c/szramy-jak-psychosystem-niszczy-nasze-dzieci-w-iext115641281.jpg',
						price: 24.99,
						releaseYear: '2020',
						title: 'Szramy. Jak psychosystem niszczy nasze dzieci',
						type: 'books',
						language: 'polski',
						pages: 288,
						publisher: 'Wielka Litera',
						authors: ['Witold Bereś', 'Janusz Schwertner'],
					},
					{
						categoryID: 13,
						description: '',
						discount: 0,
						format: 'Książka (miękka okładka)',
						id: '105',
						img: 'https://s.lubimyczytac.pl/upload/books/7000/7534/352x500.jpg',
						price: 27.99,
						releaseYear: '2006',
						title: 'Od nędzy do pieniędzy',
						type: 'books',
						language: 'polski',
						pages: 322,
						publisher: 'Fijorr Publishing',
						authors: ['Tad Witkowicz'],
					},
					{
						categoryID: 41,
						description: '',
						discount: 6,
						format: 'Płyta CD',
						id: '523',
						img: 'https://ecsmedia.pl/c/2014-forest-hills-drive-w-iext102792100.jpg',
						price: 31.99,
						releaseYear: '2014',
						title: 'Forest Hills Drive',
						type: 'albums',
						label: 'Dreamville Records',
						authors: ['J.Cole'],
					},
					{
						categoryID: 44,
						description: '',
						discount: 7.5,
						format: 'Płyta CD',
						id: '497',
						img: 'https://ecsmedia.pl/c/collapsed-in-sunbeams-w-iext120309470.jpg',
						price: 39.99,
						releaseYear: '2021',
						title: 'Collapsed in Sunbeams',
						type: 'albums',
						label: 'Transgressive',
						authors: ['Arlo Parks'],
					},
					{
						categoryID: 45,
						description: '',
						discount: 5,
						format: 'Płyta CD',
						id: '153',
						img: 'https://ecsmedia.pl/c/dirty-w-iext117188201.jpg',
						price: 33.99,
						releaseYear: '1992',
						title: 'Dirty',
						type: 'albums',
						label: 'Other Pop',
						authors: ['Sonic Youth'],
					},
					{
						categoryID: 44,
						description: '',
						discount: 9,
						format: 'Płyta CD',
						id: '579',
						img: 'https://ecsmedia.pl/c/love-letters-w-iext36399074.jpg',
						price: 32.99,
						releaseYear: '2014',
						title: 'Love Letters',
						type: 'albums',
						label: 'Warner Music Group',
						authors: ['Metronomy'],
					},
				],
				qty: 6,
				value: 164.44000000000003,
			},
			ship: {
				inpost: 'NAW01G123',
			},
		},
	},
];

module.exports = mockOrders;
